// Code generated by protoc-gen-go-error-generator. DO NOT EDIT.
// Version v1.0.0
package account

import (
	errors "github.com/classtorch/go-error-generator-examples/internal/errors"
)

var (
	SUCCESS            = &errors.Error{Code: 0, Msg: "成功"}         //成功
	TOKEN_INVALID      = &errors.Error{Code: 1, Msg: "登录失效，请重新登录"} //登录失效，请重新登录
	ACCOUNT_NOT_EXISTS = &errors.Error{Code: 2, Msg: "账号不存在"}      //账号不存在
)
