// Code generated by protoc-gen-go-error-generator. DO NOT EDIT.
// Version v1.0.0
package account

import (
	errors "github.com/classtorch/go-error-generator-examples/internal/errors"
)

var (
	SUCCESS       = &errors.Error{Code: 0, Msg: "成功"}           //成功
	UnKnown       = &errors.Error{Code: -1, Msg: "未知错误"}        //未知错误
	InValid_Phone = &errors.Error{Code: 10001, Msg: "手机号格式不正确"} //手机号格式不正确
)

var (
	Msg = map[int32]*errors.Error{
		0:     &errors.Error{Code: 0, Msg: "成功"},
		-1:    &errors.Error{Code: -1, Msg: "未知错误"},
		10001: &errors.Error{Code: 10001, Msg: "手机号格式不正确"},
	}

	Msg_English = map[int32]*errors.Error{
		0:     &errors.Error{Code: 0, Msg: "success"},
		-1:    &errors.Error{Code: -1, Msg: "unknown err"},
		10001: &errors.Error{Code: 10001, Msg: "invalid phone no"},
	}
)
